- name: install needed packages
  apt: name={{ item }} state=present
  with_items:
    - apache2
    - tftpd-hpa
    - inetutils-inetd
    - isc-dhcp-server
  sudo: yes

# To use an iso on the local machine, copy the iso to the "files" directory
# and uncomment to following play
#- name: copy ubuntu iso to server
#  copy: src=ubuntu-14.04.1-server-amd64.iso 
#        dest=~/

# If using a local iso, comment out the following play
- name: download ubuntu 14.04 server iso
  get_url: url=http://releases.ubuntu.com/14.04/ubuntu-14.04.1-server-amd64.iso 
           dest=/home/vagrant/
  sudo: yes

- name: mount iso
  shell: mount -o loop /home/vagrant/ubuntu-14.04.1-server-amd64.iso /mnt 
         creates=/mnt/ubuntu
  sudo: yes

- name: copy files from mounted .iso
  shell: mkdir /var/www/html/ubuntu;
         cp -rf /mnt/* /var/www/html/ubuntu/;
         cp -rf /mnt/install/netboot/* /var/lib/tftpboot/
         creates=/var/www/html/ubuntu
  sudo: yes

- name: copy tftpd-hpa
  copy: src=tftpd-hpa
        dest=/etc/default/
        owner=root
        group=root
        mode=644
        backup=yes
  sudo: yes
  notify:
    - restart tftp

- name: copy syslinux.cfg
  template: src=syslinux.cfg
            dest=/var/lib/tftpboot/ubuntu-installer/amd64/boot-screens/
            owner=root
            group=root
            mode=444
            backup=yes
  sudo: yes

- name: copy dhcpd.conf
  template: src=dhcpd.conf
            dest=/etc/dhcp/
            owner=root
            group=root
            mode=644
            backup=yes
  sudo: yes
  notify:
    - restart dhcp

- name: copy preseed.cfg
  template: src=preseed.cfg
            dest=/var/www/html/ubuntu/install/
            backup=yes
  sudo: yes

- name: copy ks.cfg
  template: src=ks.cfg
            dest=/var/www/html/ubuntu/install/
            backup=yes
  sudo: yes

- name: add line to initd.conf
  lineinfile: dest=/etc/inetd.conf
              state=present
              line="tftp    dgram   udp    wait    root    /usr/sbin/in.tftpd /usr/sbin/in.tftpd -s /var/lib/tftpboot"
  sudo: yes
