---
- name: Install packages
  apt: name={{ item }}
       state=present
  with_items:
    - apache2
    - php5
    - php5-mysql
    - libapache2-mod-php5
    - curl

- name: Enable mod_rewrite module
  shell: a2enmod mod_rewrite;
         touch /opt/mod_rewrite.ansible
         creates=/opt/mod_rewrite.ansible

- name: Get the latest version of wordpress
  get_url: url=https://wordpress.org/latest.tar.gz
           dest=/opt

- name: unarchive wordpress
  unarchive: src=/opt/latest.tar.gz
             dest=/opt
             copy=no
             creates=/opt/wordpress

- name: Copy wp-config.php
  template: src=wp-config.php
            dest=/var/www/html

- name: Remove wp-config-sample.php
  file: path=/opt/wordpress/wp-config-sample.php
        state=absent

- name: Copy wordpress files to root path
  shell: cp -rf /opt/wordpress/* /var/www/html/;
         rm /var/www/html/index.html;
         touch /opt/copy.ansible
         creates=/opt/copy.ansible

- name: restart apache
  service: name=apache2
           state=restarted
